### ISSUE TITLE
Wrapper for Giotto import

### ISSUE THREAD

**Issue by rbutleriii** [yunguan-wang/Spacia#50]
Hello,

Very interested in trying out Spacia, looks perfect for my use. I was wondering if you had worked with Giotto data in the past and had any wrapper script or  code for quickly extracting the expression matrices and spatial_locs by sender & receiver cell types?

Thanks

**Comment by wtwt5237** [comment]
Hi @rbutleriii

Thanks a lot for your interest!

No, we have not worked with Giotto data.

Thanks!

Tao

**Comment by wtwt5237** [comment]
Hi @rbutleriii 

Thanks for your interest again! You should explicitly specify which is the sending cell type and which is the receiving cell type. Not include all types of cells in the input to Spacia

Thanks!

Tao

**Comment by rbutleriii** [comment]
Understood, for my command, I am specifying a specific `-sc` & `rc`. like so: 
```sh
python spacia.py $mat $meta -sc 'L4 IT CTX' -rc 'MG' -sf Apoe --output_path $out
```

For the actual gene expression matrix though, I have CosMx data with 18,965 cells of all types x 950 genes. If I filter that expression matrix down to 4203 cells (Only the ASC and L4 IT CTX cells) x 950 genes and run spacia on that subset will that affect the output? Put another way. does Spacia take surrounding unrelated cell types (and their spatial position) into account when calculating its result?

**Comment by wtwt5237** [comment]
To your question: "does Spacia take surrounding unrelated cell types (and their spatial position) into account when calculating its result?"

The answer is no

Tao
